spring.application.name=spring-Contact
#spring.datasource.url=jdbc:postgresql://ep-jolly-poetry-an3kty6j.c-6.us-east-1.aws.neon.tech:5432/neondb
#spring.datasource.username=neondb_owner

#spring.datasource.url=jdbc:postgresql://ep-jolly-poetry-an3kty6j-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_vocMAkP8zK0b
#
#
#spring.profiles.active=prod
##postgresql://neondb_owner:npg_vocMAkP8zK0b@ep-jolly-poetry-an3kty6j-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#
#logging.level.root=debug
##spring.jpa.hibernate
#
#spring.jpa.hibernate.ddl-auto=update